/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package co.com.tipi.alertbutton.controller;

import co.com.tipi.alertbutton.domain.Alert;
import co.com.tipi.alertbutton.domain.ModelApiResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-07-29T23:54:40.413Z")

@Api(value = "alert", description = "the alert API")
public interface AlertApi {

    @ApiOperation(value = "Nueva alerta", nickname = "addAlert", notes = "Agregar nueva alerta", response = ModelApiResponse.class, authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "read:buttons", description = "read your experience"),
            @AuthorizationScope(scope = "write:buttons", description = "modify experience in your account")
            })
    }, tags={ "alert", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "successful operation", response = ModelApiResponse.class),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/alert",
        produces = { "application/xml; charset=utf-8", "application/json; charset=utf-8" }, 
        consumes = { "application/json; charset=utf-8", "application/xml; charset=utf-8" },
        method = RequestMethod.POST)
    ResponseEntity<ModelApiResponse> addAlert(@ApiParam(value = "Objecto botón que será agregado", required = true) @Valid @RequestBody Alert body);


    @ApiOperation(value = "Lista las alertas", nickname = "listAlert", notes = "Lista histórico de alertas", response = Alert.class, responseContainer = "List", tags={ "alert", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Alert.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid status value"),
        @ApiResponse(code = 401, message = "Unauthorized user") })
    @RequestMapping(value = "/alert",
        produces = { "application/json; charset=utf-8", "application/xml; charset=utf-8" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Alert>> listAlert(@ApiParam(value = "Teléfono") @Valid @RequestParam(value = "phone", required = false) String phone, @ApiParam(value = "Nombre") @Valid @RequestParam(value = "name", required = false) String name, @ApiParam(value = "Teléfono") @Valid @RequestParam(value = "address", required = false) String address, @ApiParam(value = "Nombre de contacto") @Valid @RequestParam(value = "contactName", required = false) String contactName, @ApiParam(value = "Teléfono de contacto") @Valid @RequestParam(value = "contactPhone", required = false) String contactPhone, @ApiParam(value = "Estado") @Valid @RequestParam(value = "status", required = false) String status, @ApiParam(value = "Fecha de inicio") @Valid @RequestParam(value = "startDate", required = false) String startDate, @ApiParam(value = "Fecha fin") @Valid @RequestParam(value = "endDate", required = false) String endDate);

}
